Roulette:
  rewardAmount: 10
  length:
    min: 40
    max: 150
inventories:
  preview:
    title: "&8Preview Menu"
    size: 45
    items:
      border:
        material: BLACK_STAINED_GLASS_PANE
        name: "&f "
        slots:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
      rewards:
        slots:
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17